[package]
name = "LrnWgpu"
version = "0.1.0"
edition = "2021"

[dependencies]
wgpu = "0.12.0"
winit = "0.27.0"
image = "0.23.14"
cgmath = "0.18.0"
env_logger = "0.9.0"
log = "0.4.14"
pollster = "0.2.5"